---
# Production environment override
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php-prod
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  messenger-worker:
    image: ${IMAGES_PREFIX:-}app-php-prod
    restart: unless-stopped
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
    depends_on:
      - redis
      - database
    environment:
      APP_ENV: prod
      
volumes:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
  redis_data:
