create table messenger_messages (
    id bigint generated by default as identity not null,
    body text not null,
    headers text not null,
    queue_name varchar(190) not null,
    created_at timestamp(0) without time zone not null,
    available_at timestamp(0) without time zone not null,
    delivered_at timestamp(0) without time zone default null, primary key (id)
);

-- migration:statement
create index "IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750"
on messenger_messages (queue_name, available_at, delivered_at, id);

-- migration:statement     
create table "user" (
    id bigint primary key generated by default as identity,
    email text not null,
    "roles" jsonb not null,
    "password" text not null
);

-- migration:statement
create unique index uniq_identifier_email on "user" (email)

-- migration:statement
create table audit (
    id bigint primary key generated by default as identity,
    created_at timestamptz default current_timestamp not null,
    "action" text not null,
    user_id bigint references "user",
    entity text null,
    entity_id bigint null,
    ip_address inet null,
    user_agent text null,
    trace_id char(32) null,
    span_id char(16) null,
    message text null,
    "data" jsonb null
);

-- migration:statement
create view reporting.audit as
select
    id,
    created_at,
    action
from public.audit;
