create table "user"
(
    id bigint primary key generated by default as identity,
    email text not null,
    "roles" jsonb not null,
    "password" text not null
);

-- migration:statement
create unique index uniq_identifier_email on "user" (email)
